ehPar x = if rem x 2 ==0 then True else False;
anoIdade idade = 2020-idade;
permiteDirigir y= if(anoIdade y)>= 18 then True else False;
zeroPosNeg x = if(x==0) then "zero" else if (x>0) then "positivo" else "negativo";
media3 a b c = div (a+b+c) 3;
areaSala a b= a*b;
minHoras x = div x 60;
dobroOuTriplo x = if(x>0)then x*2 else x*3;
ehAprovado a b c = if(media3 a b c >=7) then "Aprovado" else "Reprovado";
somaDigitos x = x-(10*(div (x-(100*(div x 100))) 10)) - 100*(div x 100) + div (x-(100*(div x 100))) 10 + div x 100;